# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-10-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20191026_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
