# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-10-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20191028_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
