# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-10-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_rmturl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
